* Introduction
nompac_rs is a wrapper for the pacman packagemanager.
The goal is, to enable a kind of descriptive package management like in nixos and the possibility to easily patch upstream packages and build new packages like in gentoo.

All configurations are done either by settings in TOML files or by giving command line arguments.

This is still a work in progress and is written for my personal needs. It can be adjusted to different installations, but it is not my goal to make nompac_rs flexible enough so that all different system setups are supported.

* Features
- Configuration of the used paths and settings in a config file.
- Definition of a list of packages that should be installed.
  Remark: Only the packages that should be manually installed need to be defined here - dependencies will still be handled by pacman.
  nompac_rs checks the list of given packages to the list of explicitely installed packages with pacman and automatically builds a list of packages to be installed or removed depending on the difference in the package lists. Then the installation or deletion process of the packages and its dependencies is handled by pacman.
- Changes to config files (e.g. etc or desktop files) can be defined. if a config file doesn't exist, it will be created with the given content.
- Define patches to be added to upstream packages
- Define new PKGBUILDs as overlays.
- Both new packages as well as patched upstream packages will be automatically build and the result added to a local repository that can be defined in the configs.
- possibility to pin a snapshot of the arch linux repository from a specific date. Updates of the system and all newly installed packages will be pulled from this snapshot.

* Usage
TODO
